[package]
name = "x509-certificate"
version = "0.12.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
description = "X.509 certificate parser and utility functionality"
keywords = ["x509", "cryptography", "pki"]
homepage = "https://github.com/indygreg/PyOxidizer"
repository = "https://github.com/indygreg/PyOxidizer.git"
readme = "README.md"

[features]
test = []

[dependencies]
bcder = "0.6"
bytes = "1.0"
chrono = { version = "=0.4.19", default-features = false, features = ["std", "clock"] }
hex = "0.4"
pem = "1.0"
ring = { git = "https://github.com/JanKaul/ring.git", branch = "wasm32-wasi" }
thiserror = "1.0"
