[package]
name = "x509-certificate"
version = "0.21.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2021"
rust-version = "1.65"
license = "MPL-2.0"
description = "X.509 certificate parser and utility functionality"
keywords = ["x509", "cryptography", "pki"]
homepage = "https://github.com/indygreg/cryptography-rs"
repository = "https://github.com/indygreg/cryptography-rs.git"
readme = "README.md"

[features]
test = []

[dependencies]
bcder = "0.7.2"
bytes = "1.4.0"
chrono = { version = "0.4.26", default-features = false, features = ["clock"] }
der = "0.7.7"
hex = "0.4.3"
pem = "2.0.1"
ring = { package = "ring-wasi", git = "https://github.com/jedisct1/ring-wasi", branch = "0.16.20" }
signature = { version = "2.1.0", features = ["std"] }
spki = { version = "0.7.2", features = ["alloc"] }
thiserror = "1.0.44"
